language: go
go:
- stable
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    repo: NoUseFreak/gitteams
    branch: master
    tags: true
env:
  global:
    secure: szNL/4Fruslmk8+JZ77hGTtREjpwTSidqTMtZ7VZmC5tzR4xLDro4XmmmeUGT1X54e4+93A6/VLgcBlNHHeeLfXyL+BHSu4kbXT6ejfP9+7cUrdL9orntvClY7VXYWB9BhIimRJnXWl+EvFMv394kj74RFV+/e8/C7wZ0DRtKEOTbSnjFVtFG3NbVt89iRWfzYv0hu7hZYtg0JMStFBDnsSaP5f3zrp9ZyIt4nfjjOxlOAHnu8f9L1FuKTjB1jNzS7qOFLlp2dRLM5g/x+gKNx3nHe1ThEDsH2Fn+/IU+lcNpZH6ktW9qxNsCp3vWxH4taYOvxHTvGteuDUrdaNhb3MEAL9B546anwSZiiAcW5QhyzWypZENL31Voszr99JYvvetEfhGMjiGYJpwx+7XOknXaXt9kBGzrUrFcDeH3r01wH8NE5/Zcl9pZjAhEPegOvhbTUkyrntOTc6o8nFcacxXxTa5BgE0owoKYnmQpW7aa2KHVMi0JLd2EmRuzrXEje0HaiJXF1CEkWbkKdntIhIi4wFd+0wIx5a+nHKOskPS4xA4vaBzZ/rRvHV82dzyngottE9qpcELSvppdUWYk4l8ShueUymBtUxXFKH4P8OVU1M5MOMvOqbtoBHkQ5vOXX0Uul+dLHMWiaQnUWeIeAIeRWolruesrsedKZQicWg=
